version: '3.1'
services:
  mysql:
    image: mysql
    command:
      --default-authentication-plugin=mysql_native_password
    restart: always
    ports:
      - 3306:3306
    environment:  # Use root/example as user/password
      MYSQL_ROOT_PASSWORD: example

  
  homefinderbackend:
    image: "node:12"
    # restart: always
    user: "node"
    working_dir: /home/node/app
    environment:
      - NODE_ENV=docker-dev
    volumes:
      - ./:/home/node/app
    ports:
      - 8000:8000
    depends_on:
      - mysql
    command: ["./wait-for-it.sh","mysql:3306","--","npm","start"]

  homefinderimages:
    image: "nginx"
    restart: always
    volumes:
      - ../homefinderimages/:/usr/share/nginx/html
    ports:
      - 8010:80

  homefinderutil:
    image: "node:12"
    # restart: always
    user: "node"
    working_dir: /home/node/app
    environment:
      - NODE_ENV=docker-dev
    volumes:
      - ../homefinderutil/:/home/node/app
    ports:
      - 8020:8020
    depends_on:
      - mysql
    command: ["./wait-for-it.sh","mysql:3306","--","npm","start"]


  adminer:
    image: adminer
    restart: always
    ports:
      - 8030:8080

